id: Add Employees to Departing Employee Watchlist
version: -1
fromversion: "6.8.0"
name: Add Employees to Departing Employee Watchlist
description: Loops through stand-down tickets provided by the Departing Employee Auto-Add
  playbook and adds employees to the Departing Employee watchlist in Code42 Incydr.
tags:
- Code42 Incydr
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b73d3693-a89e-46e8-8385-1422ee651270
    type: start
    task:
      id: b73d3693-a89e-46e8-8385-1422ee651270
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": -420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: f5f5cb05-4ce9-44dc-87b7-af91cc65ec86
    type: regular
    task:
      id: f5f5cb05-4ce9-44dc-87b7-af91cc65ec86
      version: -1
      name: Add Employee to Departing Employee Watchlist
      description: Adds a user to the Departing Employee List.
      script: Code42|||code42-departingemployee-add
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#error#':
      - "18"
      '#none#':
      - "22"
    scriptarguments:
      departuredate:
        simple: ${inputs.ticket_departure_date}
      username:
        simple: ${inputs.ticket_username}
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 640,
          "y": 60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: a87476a2-78ac-4105-85b2-811a15c5bb3f
    type: regular
    task:
      id: a87476a2-78ac-4105-85b2-811a15c5bb3f
      version: -1
      name: Query Departing Employee Watchlist for Username
      description: Retrieve departing employee details.
      script: Code42|||code42-departingemployee-get
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      username:
        simple: ${inputs.ticket_username}
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": -280
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: e5fd2eae-5e02-4e54-869a-b826086748b5
    type: condition
    task:
      id: e5fd2eae-5e02-4e54-869a-b826086748b5
      version: -1
      name: Is Username Already in Watchlist?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Code42.DepartingEmployee.Username
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": -110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 4656c778-ad64-43fd-8c29-e69f2738a24c
    type: regular
    task:
      id: 4656c778-ad64-43fd-8c29-e69f2738a24c
      version: -1
      name: Set "No Action Taken" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: No action taken on ${inputs.ticket_username}. Employee is on the Departing
          Employee watchlist with a departure date of ${inputs.ticket_departure_date}.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -315,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: d382f984-f439-4fea-8f0a-39e2441e6092
    type: regular
    task:
      id: d382f984-f439-4fea-8f0a-39e2441e6092
      version: -1
      name: Set "Added Employee" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Added ${inputs.ticket_username} to Departing Employee watchlist with
          a departure date of ${inputs.ticket_departure_date}.
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 640,
          "y": 415
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: e2375977-d1ae-4c03-83a0-587260f7ae7c
    type: condition
    task:
      id: e2375977-d1ae-4c03-83a0-587260f7ae7c
      version: -1
      name: Do Departure Dates Match?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "23"
      "Yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "Yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.ticket_departure_date
            iscontext: true
          right:
            value:
              simple: Code42.DepartingEmployee.DepartureDate
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -80,
          "y": 60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 9f997538-531d-41c0-8d9c-ac11220cce66
    type: regular
    task:
      id: 9f997538-531d-41c0-8d9c-ac11220cce66
      version: -1
      name: Set "Updated Departure" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Updated ${inputs.ticket_username}'s Incydr departure date to ${inputs.ticket_departure_date}
          based on ticket.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 160,
          "y": 415
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: 2814e148-cb7b-4ddb-89fc-2ea581c50ff2
    type: regular
    task:
      id: 2814e148-cb7b-4ddb-89fc-2ea581c50ff2
      version: -1
      name: Set "Error Adding" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Error adding ${inputs.ticket_username} to Departing Employee watchlist.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 415
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: c7202372-10bc-47fa-8283-f7eda03ac698
    type: title
    task:
      id: c7202372-10bc-47fa-8283-f7eda03ac698
      version: -1
      name: Playbook Complete
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -315,
          "y": 760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: fcb5b104-0099-479a-81ab-21d5ab425344
    type: regular
    task:
      id: fcb5b104-0099-479a-81ab-21d5ab425344
      version: -1
      name: Delete Departing Employee Context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      key:
        simple: Code42.DepartingEmployee
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -315,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: 9e26526f-13af-4b28-848d-9630df9fbf65
    type: regular
    task:
      id: 9e26526f-13af-4b28-848d-9630df9fbf65
      version: -1
      name: Update Incydr User Profile
      description: Update a user's risk profile.
      script: Code42|||code42-user-update-risk-profile
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      end_date:
        simple: ${inputs.ticket_departure_date}
      ignore-outputs:
        simple: "false"
      notes:
        complex:
          root: incident
          accessor: created
          transformers:
          - operator: Cut
            args:
              delimiter:
                value:
                  simple: T
              fields:
                value:
                  simple: "1"
          - operator: concat
            args:
              prefix:
                value:
                  simple: '[XSOAR] Added to Departing Employee watchlist on '
              suffix:
                value:
                  simple: .
      username:
        simple: ${inputs.ticket_username}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 640,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: bdff5093-50d8-4788-82bc-c0e0cccf7c1d
    type: regular
    task:
      id: bdff5093-50d8-4788-82bc-c0e0cccf7c1d
      version: -1
      name: Update Incydr Departure Date
      description: Adds a user to the Departing Employee List.
      script: Code42|||code42-departingemployee-add
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      departuredate:
        simple: ${inputs.ticket_departure_date}
      note:
        complex:
          root: incident
          accessor: created
          transformers:
          - operator: Cut
            args:
              delimiter:
                value:
                  simple: T
              fields:
                value:
                  simple: "1"
          - operator: concat
            args:
              prefix:
                value:
                  simple: '[XSOAR] Updated departure date on '
              suffix:
                value:
                  simple: .
      username:
        simple: ${inputs.ticket_username}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 160,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1245,
        "width": 1805,
        "x": -315,
        "y": -420
      }
    }
  }
inputs:
- key: ticket_username
  value: {}
  required: true
  description: The username (in email format) provided in a stand-down ticket from
    Jira, Zendesk, etc.
  playbookInputQuery: null
- key: ticket_departure_date
  value: {}
  required: true
  description: The departure date (in YYYY-MM-DD format) provided in a stand-down
    ticket from Jira, Zendesk, etc.
  playbookInputQuery: null
- key: ticket_key
  value: {}
  required: false
  description: The unique identifier of a stand-down ticket from Jira, Zendesk, etc.
    (optional).
  playbookInputQuery: null
outputs: []
