id: Remove Employees from Departing Employee Watchlist
version: -1
fromversion: 6.8.0
name: Remove Employees from Departing Employee Watchlist
description: Loops through Departing Employee watchlist entries from Code42 Incydr
  and removes employees based on specified criteria.
tags:
- Code42 Incydr
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d775ae90-6f11-4476-88a5-ef8965c192f7
    type: start
    task:
      id: d775ae90-6f11-4476-88a5-ef8965c192f7
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 460,
          "y": -190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 4e877a9c-d8ab-4620-8dc8-eb99c5fe5d85
    type: condition
    task:
      id: 4e877a9c-d8ab-4620-8dc8-eb99c5fe5d85
      version: -1
      name: Is Departure Date Before Look-Back String?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "15"
      "Yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "Yes"
      condition:
      - - operator: isBefore
          left:
            value:
              complex:
                root: inputs.incydr_departure_date
                transformers:
                - operator: DateStringToISOFormat
                  args:
                    add_utc_timezone: {}
                    dayfirst:
                      value:
                        simple: "false"
                    fuzzy: {}
                    yearfirst:
                      value:
                        simple: "true"
            iscontext: true
          right:
            value:
              complex:
                root: incident
                accessor: created
                transformers:
                - operator: ModifyDateTime
                  args:
                    variation:
                      value:
                        simple: ${relative_look_back}
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 460,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 18c48c4d-ef01-482a-8428-cb23ad756a1b
    type: regular
    task:
      id: 18c48c4d-ef01-482a-8428-cb23ad756a1b
      version: -1
      name: Remove User from Departing Employee Watchlist
      description: Removes a user from the Departing Employee List.
      script: Code42|||code42-departingemployee-remove
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#error#':
      - "13"
      '#none#':
      - "17"
    scriptarguments:
      username:
        simple: ${inputs.incydr_username}
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 940,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 1a107fb0-fefc-4246-8c55-411b3b85f083
    type: regular
    task:
      id: 1a107fb0-fefc-4246-8c55-411b3b85f083
      version: -1
      name: Check for Post-Departure File Events in Incydr
      description: Search for Code42 Incydr File Events
      script: Code42|||code42-file-events-search
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      add-to-context:
        simple: "true"
      json:
        simple: |-
          {
            "purpose": "USER_EXECUTED_SEARCH",
            "groups": [
              {
                "filterClause": "AND",
                "filters": [
                  {
                    "value": "P${inputs.look_back}D",
                    "operator": "WITHIN_THE_LAST",
                    "term": "@timestamp"
                  }
                ],
                "display": "{\"data\":{\"isMultivalue\":false},\"version\":\"v2\"}"
              },
              {
                "filterClause": "AND",
                "filters": [
                  {
                    "value": "${inputs.incydr_username}",
                    "operator": "IS",
                    "term": "user.email"
                  }
                ],
                "display": "{\"data\":{\"isMultivalue\":false},\"version\":\"v2\"}"
              }
            ],
            "pgSize": 100,
            "pgNum": 1,
            "srtKey": "@timestamp",
            "srtDir": "desc"
          }
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 700,
          "y": 320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 0e52f693-63f1-4cde-8655-14de6b547492
    type: condition
    task:
      id: 0e52f693-63f1-4cde-8655-14de6b547492
      version: -1
      name: Are There Post-Departure File Events?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Code42.SecurityData.Source.domain
            iscontext: true
          right:
            value: {}
      - - operator: isEmpty
          left:
            value:
              simple: Code42.FileEvents
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 700,
          "y": 485
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 60928eb4-6b03-4176-8614-2eacf59c14bf
    type: regular
    task:
      id: 60928eb4-6b03-4176-8614-2eacf59c14bf
      version: -1
      name: Set "Error Removing" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Attempted to remove ${inputs.incydr_username} from Departing Employee
          watchlist but encountered an error.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1390,
          "y": 830
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 2501002b-26dd-4dea-8b6b-93627f489836
    type: regular
    task:
      id: 2501002b-26dd-4dea-8b6b-93627f489836
      version: -1
      name: Set "Removed from Watchlist" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Removed ${inputs.incydr_username} from Departing Employee watchlist.
          Departure date is before defined look-back.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 940,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 492369f6-224b-493e-8f38-62aa174dc6f2
    type: regular
    task:
      id: 492369f6-224b-493e-8f38-62aa174dc6f2
      version: -1
      name: Set "No Action Taken" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: No action taken on ${inputs.incydr_username}. Departure date is within
          defined look-back.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 230,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 995ecbd4-b7da-4ce6-8fd2-e7096113c9c6
    type: regular
    task:
      id: 995ecbd4-b7da-4ce6-8fd2-e7096113c9c6
      version: -1
      name: Set "Post-Departure Activity" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Not removing ${inputs.incydr_username} because of post-departure activity.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 470,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 258e3ce7-1f0f-413e-8058-6c7462a73161
    type: regular
    task:
      id: 258e3ce7-1f0f-413e-8058-6c7462a73161
      version: -1
      name: Update Incydr User Profile
      description: Update a user's risk profile.
      script: Code42|||code42-user-update-risk-profile
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      ignore-outputs:
        simple: "false"
      notes:
        complex:
          root: incident
          accessor: created
          transformers:
          - operator: Cut
            args:
              delimiter:
                value:
                  simple: T
              fields:
                value:
                  simple: "1"
          - operator: concat
            args:
              prefix:
                value:
                  simple: '[XSOAR] Removed from Departing Employee watchlist on '
              suffix:
                value:
                  simple: .
      username:
        simple: ${inputs.incydr_username}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 940,
          "y": 830
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: e9dea2ed-65d2-4856-890d-74798b7789e8
    type: title
    task:
      id: e9dea2ed-65d2-4856-890d-74798b7789e8
      version: -1
      name: Playbook Complete
      description: commands.local.cmd.set.incident
      type: title
      iscommand: false
      brand: Builtin
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 230,
          "y": 1170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: e5f448b2-6679-4f61-8a53-e57a0b2700f8
    type: regular
    task:
      id: e5f448b2-6679-4f61-8a53-e57a0b2700f8
      version: -1
      name: Set Relative Look-Back String
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      key:
        simple: relative_look_back
      value:
        simple: ${inputs.look_back} days ago
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 460,
          "y": -40
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "3_13_#error#": 0.55
    },
    "paper": {
      "dimensions": {
        "height": 1425,
        "width": 1540,
        "x": 230,
        "y": -190
      }
    }
  }
inputs:
- key: incydr_departure_date
  value: {}
  required: true
  description: The departure date (in YYYY-MM-DD format) provided by Code42 Incydr.
  playbookInputQuery: null
- key: incydr_username
  value: {}
  required: true
  description: The username (in email format) provided by Code42 Incydr.
  playbookInputQuery: null
- key: incydr_uid
  value: {}
  required: false
  description: The unique identifier of a user provided by Code42 Incydr (optional).
  playbookInputQuery: null
- key: look_back
  value:
    simple: "30"
  required: true
  description: Number of days to compare the departure date against and check for
    post-departure activity (e.g. "30", "7", etc.). Default is 30.
  playbookInputQuery: null
outputs: []
