id: 13e6c86c-ae18-4074-8a8c-acfec29b1fbc
description: A simple playbook for blocking or unblocking a user in Code42.
inputs:
- description: Either the string "block" or "unblock".
  key: Action
  playbookInputQuery:
  required: false
  value: {}
- description: The username of the user to block or unblock in Code42.
  key: username
  playbookInputQuery:
  required: false
  value: {}
name: Code42 Change Blocked Status
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9a342074-7df0-4dd1-8a82-d7804e6082b3
      iscommand: false
      name: ""
      version: -1
    taskid: 9a342074-7df0-4dd1-8a82-d7804e6082b3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 602.5,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Code42
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: a63a96d0-a534-48ce-8e6f-83861753e106
      iscommand: false
      name: Is Code42 Available?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: a63a96d0-a534-48ce-8e6f-83861753e106
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 602.5,
          "y": 195
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.action
                transformers:
                - operator: toUpperCase
          operator: isEqualString
          right:
            value:
              simple: BLOCK
      label: block
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.action
                transformers:
                - operator: toUpperCase
          operator: isEqualString
          right:
            value:
              simple: UNBLOCK
      label: unblock
    id: "2"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "5"
      block:
      - "3"
      unblock:
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 435ab4db-7c90-42fe-8c5c-4d195b5d52a4
      iscommand: false
      name: Is Block or Unblock?
      type: condition
      version: -1
    taskid: 435ab4db-7c90-42fe-8c5c-4d195b5d52a4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        simple: ${inputs.username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Code42
      description: Blocks a user in Code42.  A blocked user is not allowed to log
        in or restore files. Backups will continue if the user is still active.
      id: fcfd80be-6e52-409f-8d89-8d38a18b56c9
      iscommand: true
      name: Block User
      script: Code42|||code42-user-block
      type: regular
      version: -1
    taskid: fcfd80be-6e52-409f-8d89-8d38a18b56c9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        simple: ${inputs.username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Code42
      description: Removes a block, if one exists, on the user with the given user
        ID. Unblocked users are allowed to log in and restore.
      id: a92925e8-749c-4d05-8ef1-f68f72ed4d98
      iscommand: true
      name: Unblock User
      script: Code42|||code42-user-unblock
      type: regular
      version: -1
    taskid: a92925e8-749c-4d05-8ef1-f68f72ed4d98
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d9a6c88f-b5e1-4c92-850a-99b4f59908aa
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d9a6c88f-b5e1-4c92-850a-99b4f59908aa
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 490,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 932.5,
        "x": 50,
        "y": 50
      }
    }
  }
