id: Add Employees to New Hire Watchlist
version: -1
fromversion: "6.8.0"
name: Add Employees to New Hire Watchlist
description: Loops through stand-up tickets provided by the New Hire Auto-Add playbook
  and adds employees to the New Hire watchlist in Code42 Incydr.
tags:
- Code42 Incydr
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 59df06b9-b554-44da-80b2-e2eac2d5b8f9
    type: start
    task:
      id: 59df06b9-b554-44da-80b2-e2eac2d5b8f9
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 235,
          "y": -250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: d06f9f06-5c7f-42af-8619-d791401f8d2d
    type: regular
    task:
      id: d06f9f06-5c7f-42af-8619-d791401f8d2d
      version: -1
      name: Add User to New Hire Watchlist
      description: Add a user to a watchlist.
      script: Code42|||code42-watchlists-add-user
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#error#':
      - "18"
      '#none#':
      - "24"
    scriptarguments:
      username:
        simple: ${inputs.ticket_username}
      watchlist:
        simple: NEW_EMPLOYEE
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 460,
          "y": 60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: faf3a096-0b81-4c56-800b-2e691bd283e8
    type: condition
    task:
      id: faf3a096-0b81-4c56-800b-2e691bd283e8
      version: -1
      name: Is Username Already in Watchlist?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "Yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "Yes"
      condition:
      - - operator: inList
          left:
            value:
              simple: inputs.ticket_username
            iscontext: true
          right:
            value:
              simple: Code42.WatchlistUsers.Username
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 235,
          "y": -110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 0b24a979-3119-43ee-849c-90fb509c907f
    type: regular
    task:
      id: 0b24a979-3119-43ee-849c-90fb509c907f
      version: -1
      name: Set "No Action Taken" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: No action taken on ${inputs.ticket_username}. Employee is in the New
          Hire watchlist with a start date of ${inputs.ticket_start_date}.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 10,
          "y": 60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 8fcc4eb3-d69b-4739-86c2-e22d75165dfa
    type: regular
    task:
      id: 8fcc4eb3-d69b-4739-86c2-e22d75165dfa
      version: -1
      name: Set "Added User" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Added ${inputs.ticket_username} to New Hire watchlist with a start
          date of ${inputs.ticket_start_date}.
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 460,
          "y": 405
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: d3d142b2-cb9e-4409-8278-332718940f04
    type: regular
    task:
      id: d3d142b2-cb9e-4409-8278-332718940f04
      version: -1
      name: Set "Error Adding" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Error adding ${inputs.ticket_username} to New Hire watchlist.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 2202dbcf-1bce-49d4-8f24-756331ffbb93
    type: title
    task:
      id: 2202dbcf-1bce-49d4-8f24-756331ffbb93
      version: -1
      name: Playbook Complete
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 10,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: 1e70dec7-2b85-4747-8770-455f32bd9579
    type: regular
    task:
      id: 1e70dec7-2b85-4747-8770-455f32bd9579
      version: -1
      name: Delete New Hire Context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      key:
        simple: Code42.WatchlistUser
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 10,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "24":
    id: "24"
    taskid: 000d65d9-6ab8-462b-8ac1-4314b5831106
    type: regular
    task:
      id: 000d65d9-6ab8-462b-8ac1-4314b5831106
      version: -1
      name: Update Incydr User Profile
      description: Update a user's risk profile.
      script: Code42|||code42-user-update-risk-profile
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      ignore-outputs:
        simple: "false"
      notes:
        complex:
          root: incident
          accessor: created
          transformers:
          - operator: Cut
            args:
              delimiter:
                value:
                  simple: T
              fields:
                value:
                  simple: "1"
          - operator: concat
            args:
              prefix:
                value:
                  simple: '[XSOAR] Added to New Hire watchlist on '
              suffix:
                value:
                  simple: .
      start_date:
        simple: ${inputs.ticket_start_date}
      username:
        simple: ${inputs.ticket_username}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 460,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1065,
        "width": 1280,
        "x": 10,
        "y": -250
      }
    }
  }
inputs:
- key: ticket_username
  value: {}
  required: true
  description: The username (in email format) provided in a stand-up ticket from Jira,
    Zendesk, etc.
  playbookInputQuery: null
- key: ticket_start_date
  value: {}
  required: true
  description: The start date (in YYYY-MM-DD format) provided in a stand-up ticket
    from Jira, Zendesk, etc.
  playbookInputQuery: null
- key: ticket_key
  value: {}
  required: false
  description: The unique identifier of a stand-up ticket from Jira, Zendesk, etc.
    (optional).
  playbookInputQuery: null
outputs: []
