id: New Hire Auto-Add
version: -1
name: New Hire Auto-Add
description: Queries stand-up tickets from a ticketing system and passes relevant employee data to the Add Employees to New Hire Watchlist playbook.
tags:
- Code42 Incydr
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: cfe1ecab-9e34-4146-8293-38c0015e7211
    type: start
    task:
      id: cfe1ecab-9e34-4146-8293-38c0015e7211
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": -830
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: afdbd5ad-c846-4091-8211-0791010d209e
    type: title
    task:
      id: afdbd5ad-c846-4091-8211-0791010d209e
      version: -1
      name: Playbook Complete
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": 1025
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: ca81e831-1571-4e88-807f-f944110f7d8a
    type: regular
    task:
      id: ca81e831-1571-4e88-807f-f944110f7d8a
      version: -1
      name: Query Stand-Up Tickets
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: jira-v2
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      key:
        simple: Ticket
      value:
        simple: Replace this task with input from a ticketing system and direct the output to a key called Ticket.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": -690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 9e301572-443b-4d17-88cf-d7072fed0a9d
    type: regular
    task:
      id: 9e301572-443b-4d17-88cf-d7072fed0a9d
      version: -1
      name: Count Number of Tickets
      description: Count an array size
      scriptName: CountArraySize
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      array:
        simple: ${Ticket}
      contextKey:
        simple: ticket_count
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -190,
          "y": -180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 4462c968-c990-468e-8d23-00a7c6c79d91
    type: regular
    task:
      id: 4462c968-c990-468e-8d23-00a7c6c79d91
      version: -1
      name: Delete All Context Except Log
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: Ticket,ticket_count,Code42
      subplaybook:
        simple: "yes"
      keysToKeep:
        simple: Log
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": 680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 89ca3220-4923-4421-8563-b3d70f34eafb
    type: condition
    task:
      id: 89ca3220-4923-4421-8563-b3d70f34eafb
      version: -1
      name: Are There Open Tickets?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "Yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "Yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Ticket
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": -350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 8b1dcd8e-73cc-456a-84ca-7791f5ad077f
    type: regular
    task:
      id: 8b1dcd8e-73cc-456a-84ca-7791f5ad077f
      version: -1
      name: Set "No Tickets" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Found no open tickets.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": -180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: bef23f88-e173-4576-8a41-2ce1acad7de0
    type: regular
    task:
      id: bef23f88-e173-4576-8a41-2ce1acad7de0
      version: -1
      name: Write Log to Incident War Room
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      value:
        simple: ${Log}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: c1f452cc-61db-417f-8ef6-a2e75060c4df
    type: playbook
    task:
      id: c1f452cc-61db-417f-8ef6-a2e75060c4df
      version: -1
      name: Add Employees to New Hire Watchlist
      description: Loops through stand-up tickets provided by the New Hire Auto-Add playbook and adds employees to the New Hire watchlist in Code42 Incydr.
      playbookName: Add Employees to New Hire Watchlist
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      ticket_key:
        simple: ${Ticket.key}
      ticket_start_date:
        simple: ${Ticket.start_date}
      ticket_username:
        simple: ${Ticket.username}
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": -190,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: aa941916-a34a-49ba-8d43-d4ae0896d2b3
    type: regular
    task:
      id: aa941916-a34a-49ba-8d43-d4ae0896d2b3
      version: -1
      name: Set "Ticket Count" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Retrieved ${ticket_count} ticket(s).
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -190,
          "y": -5
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 1de5e1fa-a150-4219-8c66-33a8ccdfa20b
    type: regular
    task:
      id: 1de5e1fa-a150-4219-8c66-33a8ccdfa20b
      version: -1
      name: Set "Job Complete" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Finished New Hire Auto-Add Job.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": 510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: b121f0ad-4394-45a8-8ed4-ac9df4d6e60c
    type: regular
    task:
      id: b121f0ad-4394-45a8-8ed4-ac9df4d6e60c
      version: -1
      name: Query New Hire Watchlist
      description: List all users who have been explicitly added to a given watchlist.
      script: Code42|||code42-watchlists-list-included-users
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      watchlist:
        simple: NEW_EMPLOYEE
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -190,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: d324592a-6437-40d3-89bd-ba4c1b88fa17
    type: regular
    task:
      id: d324592a-6437-40d3-89bd-ba4c1b88fa17
      version: -1
      name: Set "Job Starting" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Beginning New Hire Auto-Add Job.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": -520
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1920,
        "width": 840,
        "x": -190,
        "y": -830
      }
    }
  }
inputs: []
outputs: []
tests:
- Code42 File Search Test
fromversion: 6.8.0
