id: Code42 File Download
version: -1
name: Code42 File Download
description: This playbook downloads a file via Code42 by either MD5 or SHA256 hash.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: eaa8ea6a-0b1b-46f0-8727-6380a03c1ff9
    type: start
    task:
      id: eaa8ea6a-0b1b-46f0-8727-6380a03c1ff9
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 9c23be0e-46e6-4434-8dd1-a8779e648074
    type: condition
    task:
      id: 9c23be0e-46e6-4434-8dd1-a8779e648074
      version: -1
      name: Is Code42 Integration Active?
      description: Checks to see if a Code42 Integration is active.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: brand
                      iscontext: true
                    right:
                      value:
                        simple: Code42
                - - operator: isEqualString
                    left:
                      value:
                        simple: state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 304a0f12-81ed-4d8d-8b2d-0a38716db95c
    type: condition
    task:
      id: 304a0f12-81ed-4d8d-8b2d-0a38716db95c
      version: -1
      name: What type of hash was supplied?
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      MD5:
      - "6"
      SHA256:
      - "5"
    separatecontext: false
    conditions:
    - label: MD5
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.MD5
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.Filename
            iscontext: true
    - label: SHA256
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.SHA256
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.Filename
            iscontext: true
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 30a9e7c6-652b-4438-8e8d-79a034b47eb8
    type: regular
    task:
      id: 30a9e7c6-652b-4438-8e8d-79a034b47eb8
      version: -1
      name: Code42 Download by SHA256
      description: Downloads a file from Code42 servers.
      script: Code42|||code42-download-file
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      filename:
        simple: ${inputs.Filename}
      hash:
        simple: ${inputs.SHA256}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 630,
          "y": 600
        }
      }
    note: false
    evidencedata:
      description:
        simple: The file that caused the alert.
      customfields: {}
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 222f4dde-d084-4b1f-8619-2318bcfe2ece
    type: regular
    task:
      id: 222f4dde-d084-4b1f-8619-2318bcfe2ece
      version: -1
      name: Code42 Download by MD5
      description: Downloads a file from Code42 servers.
      script: Code42|||code42-download-file
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      filename:
        simple: ${inputs.Filename}
      hash:
        simple: ${inputs.MD5}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 100,
          "y": 590
        }
      }
    note: false
    evidencedata:
      description:
        simple: The file that caused the alert.
      customfields: {}
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 32d89296-8200-4865-802a-f45dfdfec824
    type: title
    task:
      id: 32d89296-8200-4865-802a-f45dfdfec824
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 775
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 790,
        "width": 910,
        "x": 100,
        "y": 50
      }
    }
  }
inputs:
- key: MD5
  value:
    complex:
      root: File
      accessor: MD5
      transformers:
      - operator: uniq
  required: false
  description: MD5 hash to search for
  playbookInputQuery:
- key: SHA256
  value:
    complex:
      root: File
      accessor: SHA256
      transformers:
      - operator: uniq
  required: false
  description: SHA256 hash to search for
  playbookInputQuery:
- key: Filename
  value: {}
  required: false
  description: The name of the file to save as.
  playbookInputQuery:
outputs:
- contextPath: File.Size
  description: The size of the file.
- contextPath: File.SHA1
  description: The SHA1 hash of the file.
- contextPath: File.SHA256
  description: The SHA256 hash of the file.
- contextPath: File.Name
  description: The name of the file.
- contextPath: File.SSDeep
  description: The SSDeep hash of the file.
- contextPath: File.EntryID
  description: The entry ID of the file.
- contextPath: File.Info
  description: File information.
- contextPath: File.Type
  description: The file type.
- contextPath: File.MD5
  description: The MD5 hash of the file.
- contextPath: File.Extension
  description: The file extension.
fromversion: 5.0.0
tests:
- No Test
