id: Get Code42 Employee Information
version: -1
name: Get Code42 Employee Information
description: Receives usernames from a Code42 Incydr alert and queries Active Directory for employee and supervisor information, if applicable.
tags:
- Code42 Incydr
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c8acc6bb-66ab-471b-818a-610af410ff2e
    type: start
    task:
      id: c8acc6bb-66ab-471b-818a-610af410ff2e
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: d84d1818-f4b9-4efb-87da-89af67b9d973
    type: condition
    task:
      id: d84d1818-f4b9-4efb-87da-89af67b9d973
      version: -1
      name: Is Input an Email, Display Name, or Username?
      description: Retrieves detailed information about a user account. The user can be specified by name, email address, or as an Active Directory Distinguished Name (DN). If no filter is specified, all users are returned.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      Display Name:
      - "3"
      Email:
      - "2"
    separatecontext: false
    conditions:
    - label: Email
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.user
                transformers:
                - operator: RegexExtractAll
                  args:
                    error_if_no_match: {}
                    ignore_case: {}
                    multi_line: {}
                    period_matches_newline: {}
                    regex:
                      value:
                        simple: .*@.*
            iscontext: true
          right:
            value: {}
    - label: Display Name
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.user
                transformers:
                - operator: RegexExtractAll
                  args:
                    error_if_no_match: {}
                    ignore_case: {}
                    multi_line: {}
                    period_matches_newline: {}
                    regex:
                      value:
                        simple: '[ ]+'
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 88f0da6c-e8e1-4e86-806d-2bd09c11d424
    type: regular
    task:
      id: 88f0da6c-e8e1-4e86-806d-2bd09c11d424
      version: -1
      name: Query Active Directory via Email
      description: Retrieves detailed information about a user account. The user can be specified by name, email address, or as an Active Directory Distinguished Name (DN). If no filter is specified, all users are returned.
      script: Active Directory Query v2|||ad-get-user
      type: regular
      iscommand: true
      brand: Active Directory Query v2
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      attributes:
        simple: department
      email:
        simple: ${inputs.user}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 1d04ca9c-d3e5-4a17-8ecb-71aab3847141
    type: regular
    task:
      id: 1d04ca9c-d3e5-4a17-8ecb-71aab3847141
      version: -1
      name: Query Active Directory via Display Name
      description: Retrieves detailed information about a user account. The user can be specified by name, email address, or as an Active Directory Distinguished Name (DN). If no filter is specified, all users are returned.
      script: Active Directory Query v2|||ad-get-user
      type: regular
      iscommand: true
      brand: Active Directory Query v2
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      attributes:
        simple: department
      name:
        simple: ${inputs.user}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: acadc282-86f9-42c9-8e48-1fc21bd5c971
    type: regular
    task:
      id: acadc282-86f9-42c9-8e48-1fc21bd5c971
      version: -1
      name: Query Active Directory via Username
      description: Retrieves detailed information about a user account. The user can be specified by name, email address, or as an Active Directory Distinguished Name (DN). If no filter is specified, all users are returned.
      script: Active Directory Query v2|||ad-get-user
      type: regular
      iscommand: true
      brand: Active Directory Query v2
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      attributes:
        simple: department
      username:
        simple: ${inputs.user}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: f1404d58-fad1-4919-8c46-7c59b2765428
    type: condition
    task:
      id: f1404d58-fad1-4919-8c46-7c59b2765428
      version: -1
      name: Does Incident ID Exist?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.incidentid
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 220,
          "y": 1380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: abb25134-3936-4bfe-891e-637c7a696985
    type: regular
    task:
      id: abb25134-3936-4bfe-891e-637c7a696985
      version: -1
      name: Set Manager Incident Info
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      employeemanageremail:
        simple: ${ManagerAccount.attributes.mail}
      employeemanagername:
        simple: ${ManagerAccount.attributes.displayName}
      id:
        simple: ${inputs.incidentid}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 220,
          "y": 1560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 256e0435-e1b5-4fec-8b04-030b840a5c01
    type: title
    task:
      id: 256e0435-e1b5-4fec-8b04-030b840a5c01
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: d935687d-9cf5-480f-849a-292fd25f8928
    type: regular
    task:
      id: d935687d-9cf5-480f-849a-292fd25f8928
      version: -1
      name: Query Active Directory for Manager
      description: Retrieves detailed information about a user account. The user can be specified by name, email address, or as an Active Directory Distinguished Name (DN). If no filter is specified, all users are returned.
      script: Active Directory Query v2|||ad-get-user
      type: regular
      iscommand: true
      brand: Active Directory Query v2
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      attributes:
        simple: department
      dn:
        simple: ${Account.Manager}
      extend-context:
        simple: ManagerAccount=.
      ignore-outputs:
        simple: "true"
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 220,
          "y": 1205
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: f133ddbf-ca00-41a6-8321-a1fb1142fb2d
    type: title
    task:
      id: f133ddbf-ca00-41a6-8321-a1fb1142fb2d
      version: -1
      name: Get Manager Data
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 4107a83c-88cd-4761-85fd-f007084c0857
    type: condition
    task:
      id: 4107a83c-88cd-4761-85fd-f007084c0857
      version: -1
      name: Does Manager Attribute Exist?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Account.Manager
            iscontext: true
          right:
            value: {}
      - - operator: isNotEmpty
          left:
            value:
              simple: Account.Manager
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1030
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 6e32b95c-1baa-490f-8169-589de4a11821
    type: regular
    task:
      id: 6e32b95c-1baa-490f-8169-589de4a11821
      version: -1
      name: Set Employee Incident Info
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      employeedepartment:
        simple: ${Account.department}
      employeedisplayname:
        simple: ${Account.DisplayName}
      employeeemail:
        simple: ${Account.Email}
      id:
        simple: ${inputs.incidentid}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 220,
          "y": 860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: bc4e1575-532d-4b71-87b0-e1a719a82630
    type: condition
    task:
      id: bc4e1575-532d-4b71-87b0-e1a719a82630
      version: -1
      name: Does Incident ID Exist?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.incidentid
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "10_7_#default#": 0.26,
      "12_10_#default#": 0.53,
      "12_11_yes": 0.49,
      "5_6_yes": 0.38,
      "5_7_#default#": 0.24
    },
    "paper": {
      "dimensions": {
        "height": 1745,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: user
  value: {}
  required: true
  description: The username to query in Active Directory.
  playbookInputQuery:
- key: incidentid
  value: {}
  required: false
  description: The Palo Alto XSOAR incident ID that receives the employee information (optional).
  playbookInputQuery:
outputs:
- contextPath: Account.DisplayName
  description: The display name of the user.
  type: string
- contextPath: Account.Manager
  description: The manager of the user.
  type: string
- contextPath: Account.Username
  description: The samAccountName of the user.
  type: string
- contextPath: Account.Email
  description: The email address of the user.
  type: string
- contextPath: Account.department
  description: The Department of the user.
  type: string
tests:
- No tests (auto formatted)
fromversion: 6.8.0
