id: New Hire Auto-Add
version: -1
fromversion: 6.8.0
name: New Hire Auto-Add
description: Queries stand-up tickets from a ticketing system and passes relevant
  employee data to the Add Employees to New Hire Watchlist playbook.
tags:
- Code42 Incydr
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 516f439e-6fe9-4d45-8ce2-3f9fe4fca1f6
    type: start
    task:
      id: 516f439e-6fe9-4d45-8ce2-3f9fe4fca1f6
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": -830
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 05c90160-f09a-462b-84c8-ba265bdd035f
    type: title
    task:
      id: 05c90160-f09a-462b-84c8-ba265bdd035f
      version: -1
      name: Playbook Complete
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": 855
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: a324257b-d602-422c-8489-3d31b9504b09
    type: regular
    task:
      id: a324257b-d602-422c-8489-3d31b9504b09
      version: -1
      name: Query Stand-Up Tickets
      description: "This task is meant to be edited/replaced with one that makes a
        query to a ticketing or HR system for newly hired employees. \n        \nFor
        example, if your company's employee lifecycle process includes creating a
        new Jira ticket when an employee starts work, you would set this task to query
        Jira tickets for the relevant project or subject and extract appropriate fields
        from the ticket.\n\nIf the query returns any results, it should set a list
        of `Ticket` objects in the context, with one required property `Ticket.username`
        (the email address that matches the Code42 user account), and an optional
        `Ticket.departure_date` property (in YYYY-MM-DD format)."
      scriptName: Set
      type: regular
      iscommand: false
      brand: jira-v2
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      key:
        simple: Ticket
      value:
        simple: Replace this task with input from a ticketing system and direct the
          output to a key called Ticket. See "Details" tab for more information.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": -690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 82287946-0c7b-4fe2-8eba-304a906c0481
    type: regular
    task:
      id: 82287946-0c7b-4fe2-8eba-304a906c0481
      version: -1
      name: Delete All Context Except Log
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: Ticket,ticket_count,Code42
      subplaybook:
        simple: "yes"
      keysToKeep:
        simple: Log
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": 510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 53db0567-7501-44e6-809b-7e0222975f0c
    type: condition
    task:
      id: 53db0567-7501-44e6-809b-7e0222975f0c
      version: -1
      name: Are There Open Tickets?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "Yes":
      - "19"
    separatecontext: false
    conditions:
    - label: "Yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Ticket
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": -350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 1b83b69b-54b9-4703-8839-6e08af1e4bbd
    type: regular
    task:
      id: 1b83b69b-54b9-4703-8839-6e08af1e4bbd
      version: -1
      name: Set "No Tickets" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Found no open tickets.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": -180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 0abbc216-2427-4e2c-842b-bc337698e334
    type: regular
    task:
      id: 0abbc216-2427-4e2c-842b-bc337698e334
      version: -1
      name: Write Log to Incident War Room
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      value:
        simple: ${Log}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": 680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: 14aad8d6-dfc5-4c1b-8173-707dd41ed5e7
    type: playbook
    task:
      id: 14aad8d6-dfc5-4c1b-8173-707dd41ed5e7
      version: -1
      name: Add Employees to New Hire Watchlist
      description: Loops through stand-up tickets provided by the New Hire Auto-Add
        playbook and adds employees to the New Hire watchlist in Code42 Incydr.
      playbookName: Add Employees to New Hire Watchlist
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      ticket_key:
        simple: ${Ticket.key}
      ticket_start_date:
        simple: ${Ticket.start_date}
      ticket_username:
        simple: ${Ticket.username}
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": -190,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 3a8b1308-ca89-4410-88c3-282a49009d23
    type: regular
    task:
      id: 3a8b1308-ca89-4410-88c3-282a49009d23
      version: -1
      name: Set "Retrieved Ticket(s)" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Retrieved stand-up ticket(s).
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -190,
          "y": -180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 9182e12d-2f63-4e30-8413-476246435da5
    type: regular
    task:
      id: 9182e12d-2f63-4e30-8413-476246435da5
      version: -1
      name: Set "Job Complete" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Finished New Hire Auto-Add Job.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 270,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: 63ad0694-c936-4afd-8f04-a19adddb8a59
    type: regular
    task:
      id: 63ad0694-c936-4afd-8f04-a19adddb8a59
      version: -1
      name: Query New Hire Watchlist
      description: List all users who have been explicitly added to a given watchlist.
      script: Code42|||code42-watchlists-list-included-users
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      watchlist:
        simple: NEW_EMPLOYEE
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -190,
          "y": 0
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: 9b75881b-9d1e-418c-85b2-c2607168b272
    type: regular
    task:
      id: 9b75881b-9d1e-418c-85b2-c2607168b272
      version: -1
      name: Set "Job Starting" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Beginning New Hire Auto-Add Job.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": -520
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1750,
        "width": 840,
        "x": -190,
        "y": -830
      }
    }
  }
inputs: []
outputs: []
