id: Departing Employee Auto-Add
version: -1
fromversion: "6.8.0"
name: Departing Employee Auto-Add
description: Queries stand-down tickets from a ticketing system and passes relevant
  employee data to the Add Employees to Departing Employee Watchlist playbook. Intended
  to be run as a scheduled job.
tags:
- Code42 Incydr
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a1f43b65-4db4-41e7-8d22-4e53863759e8
    type: start
    task:
      id: a1f43b65-4db4-41e7-8d22-4e53863759e8
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": -760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 00984293-7eb3-4b45-88c3-2d1c7471fadf
    type: title
    task:
      id: 00984293-7eb3-4b45-88c3-2d1c7471fadf
      version: -1
      name: Playbook Complete
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 330,
          "y": 755
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 304b6e68-503f-4256-8fef-33cd72231384
    type: regular
    task:
      id: 304b6e68-503f-4256-8fef-33cd72231384
      version: -1
      name: Query Stand-Down Tickets
      description: |-
        This task is meant to be edited/replaced with one that makes a query to a ticketing or HR system for new
        departing employees. 
        
        For example, if your company's employee lifecycle process includes creating a new Jira
        ticket when an employee gives notice, you would set this task to query Jira tickets for the relevant project or
        subject and extract appropriate fields from the ticket.
        
        If the query returns any results, it should set a list of `Ticket` objects in the context,
        with one required property `Ticket.username` (the email address that matches the Code42 user account), and an 
        optional `Ticket.departure_date` property (in YYYY-MM-DD format).
      scriptName: Set
      type: regular
      iscommand: false
      brand: jira-v2
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      key:
        simple: Ticket
      value:
        simple: Replace this task with input from a ticketing system and direct the
          output to a key called Ticket. See "Details" tab for more information.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": -620
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 2b3fa71a-84ae-442c-8efa-11f404882111
    type: regular
    task:
      id: 2b3fa71a-84ae-442c-8efa-11f404882111
      version: -1
      name: Delete All Context Except Log
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: Code42,Ticket,ticket_count
      keysToKeep:
        simple: Log
      subplaybook:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 330,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 54a8ca8a-46d7-45df-87b4-31420729caab
    type: condition
    task:
      id: 54a8ca8a-46d7-45df-87b4-31420729caab
      version: -1
      name: Are There Open Tickets?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "17"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Ticket
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": -280
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: f8f4b21e-0148-42c8-8a85-86d8278750ff
    type: regular
    task:
      id: f8f4b21e-0148-42c8-8a85-86d8278750ff
      version: -1
      name: Set "No Tickets" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Found no open tickets.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 330,
          "y": -110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: c6b3aa53-2470-47d9-8a89-b3c309bea431
    type: regular
    task:
      id: c6b3aa53-2470-47d9-8a89-b3c309bea431
      version: -1
      name: Write Log to Incident War Room
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      value:
        simple: ${Log}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 330,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: f6a29705-5db3-42c2-89bc-7d2e83a43c55
    type: regular
    task:
      id: f6a29705-5db3-42c2-89bc-7d2e83a43c55
      version: -1
      name: Set "Retrieved Ticket(s)" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Retrieved stand-down ticket(s).
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -220,
          "y": -110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: a85d42ec-1d03-416a-8588-45ba70c999dd
    type: regular
    task:
      id: a85d42ec-1d03-416a-8588-45ba70c999dd
      version: -1
      name: Set "Job Complete" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Finished Departing Employee Auto-Add Job.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 330,
          "y": 240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: a54a0f62-1110-40cd-8afa-de98c4a3b03d
    type: playbook
    task:
      id: a54a0f62-1110-40cd-8afa-de98c4a3b03d
      version: -1
      name: Add Employees to Departing Employee Watchlist
      description: Loops through stand-down tickets provided by the Departing Employee
        Auto-Add playbook and adds employees to the Departing Employee watchlist in
        Code42 Incydr.
      playbookName: Add Employees to Departing Employee Watchlist
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      ticket_departure_date:
        simple: ${Ticket.departure_date}
      ticket_key:
        simple: ${Ticket.key}
      ticket_username:
        simple: ${Ticket.username}
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
      forEach: true
    view: |-
      {
        "position": {
          "x": -220,
          "y": 65
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: 8d460d24-0623-46ec-809c-8c9f0d0b5344
    type: regular
    task:
      id: 8d460d24-0623-46ec-809c-8c9f0d0b5344
      version: -1
      name: Set "Job Starting" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Beginning Departing Employee Auto-Add Job.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": -450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1580,
        "width": 930,
        "x": -220,
        "y": -760
      }
    }
  }
inputs: []
outputs: []
