id: Code42 Copy File To Ticketing System
version: -1
name: Code42 Copy File To Ticketing System
description: Downloads a file from Code42 and attaches it to a ticketing system. This playbook uses Jira out-of-the-box, but you can swap it with a different Ticketing system and achieve the same result. For example, to use ServiceNow, change the command `jira-issue-upload-file` to be `servicenow-upload-file` and use the `id` parameter for `issueId` and `file_id` for `entryId`.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: fed44edd-ce2f-44f7-8671-63579af89d01
    type: start
    task:
      id: fed44edd-ce2f-44f7-8671-63579af89d01
      version: -1
      name: ""
      description: The start task.
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": -150
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: 31ccfbe7-73aa-4ce7-8c83-1abb21e0ff2b
    type: title
    task:
      id: 31ccfbe7-73aa-4ce7-8c83-1abb21e0ff2b
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "24":
    id: "24"
    taskid: a20a49c7-c5bd-449b-8586-586513f08bf2
    type: regular
    task:
      id: a20a49c7-c5bd-449b-8586-586513f08bf2
      version: -1
      name: Download File
      description: Downloads a file from Code42 servers.
      script: Code42|||code42-download-file
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      filename:
        simple: ${inputs.Filename}
      hash:
        simple: ${inputs.Hash}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -20,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "25":
    id: "25"
    taskid: 1451f320-7e82-4d17-851f-d879fa6682b9
    type: regular
    task:
      id: 1451f320-7e82-4d17-851f-d879fa6682b9
      version: -1
      name: Upload to Ticketing System
      description: Uploads a file attachment to an issue.
      script: jira-v2|||jira-issue-upload-file
      type: regular
      iscommand: true
      brand: jira-v2
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      attachmentName:
        complex:
          root: File
          accessor: Name
          transformers:
            - operator: LastArrayElement
      issueId:
        simple: ${inputs.IssueId}
      upload:
        complex:
          root: File
          accessor: EntryID
          transformers:
            - operator: LastArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -20,
          "y": 535
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "26":
    id: "26"
    taskid: c922f7af-41e4-48cd-8dc5-9140b61c1f46
    type: condition
    task:
      id: c922f7af-41e4-48cd-8dc5-9140b61c1f46
      version: -1
      name: Is Code42 available?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "23"
      "yes":
      - "27"
    scriptarguments:
      brandname:
        simple: Code42
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 460,
          "y": -10
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "27":
    id: "27"
    taskid: cbdf6e77-a3eb-4a19-8842-e4081cec0d71
    type: condition
    task:
      id: cbdf6e77-a3eb-4a19-8842-e4081cec0d71
      version: -1
      name: Is Jira available?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "23"
      "yes":
      - "24"
    scriptarguments:
      brandname:
        simple: jira-v2
    results:
    - brandInstances
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 460,
          "y": 140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 935,
        "width": 860,
        "x": -20,
        "y": -150
      }
    }
  }
inputs:
- key: Hash
  value: {}
  required: true
  description: The hash of the file to download from Code42 and attach to the ticketing system.
  playbookInputQuery:
- key: IssueId
  value: {}
  required: true
  description: The ID of the Ticket to upload the file to.
  playbookInputQuery:
- key: Filename
  value: {}
  required: false
  description: The name of the file to download/upload.
  playbookInputQuery:
outputs: []
fromversion: 5.0.0
tests:
- No tests (auto formatted)
