id: Code42 Suspicious Activity Review
version: -1
name: Code42 Suspicious Activity Review
description: Detects suspicious activities of a user and allows a recipient to assess the results. Afterward, the playbook takes action on the user such as adding them to legal hold.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 02629255-2522-4558-8ec4-8ff1fe049104
    type: start
    task:
      id: 02629255-2522-4558-8ec4-8ff1fe049104
      version: -1
      name: ""
      description: The start task.
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 2e1fb6fe-120b-460d-8fd4-f858fa07237f
    type: regular
    task:
      id: 2e1fb6fe-120b-460d-8fd4-f858fa07237f
      version: -1
      name: Retrieve Exfiltration Events
      description: Searches for a file in Security Data by JSON query, hash, username, device hostname, exfiltration type, or a combination of parameters. At least one argument must be passed in the command. If a JSON argument is passed, it will be used to the exclusion of other parameters, otherwise parameters will be combined with an AND clause.
      script: '|||code42-securitydata-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      exposure:
        simple: All
      username:
        simple: ${inputs.Username}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 814b7dcb-1bd3-4ea5-8774-f8d770d564c9
    type: title
    task:
      id: 814b7dcb-1bd3-4ea5-8774-f8d770d564c9
      version: -1
      name: Complete
      description: Complete
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -20,
          "y": 1490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 81c1d131-cb35-4090-8685-4425453a4e06
    type: collection
    task:
      id: 81c1d131-cb35-4090-8685-4425453a4e06
      version: -1
      name: Request Manager Review
      description: Emails the exposure events to the recipient with a survey asking if the events seem suspicious.
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 875
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: ${inputs.ReviewerEmail}
      subject:
        simple: Possible data exposure risk detected for ${inputs.Username}. Respond using link below.
      body:
        complex:
          root: HTMLTable
          transformers:
          - operator: Stringify
          - operator: concat
            args:
              prefix:
                value:
                  simple: Use the data in the table below to determine if the activity is suspicious. The link to the survey is found below the table.
              suffix: {}
      methods:
      - email
      format: html
      bcc:
      cc:
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: false
        completeaftersla: false
      replyOptions:
      - "Yes"
      - "No"
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: Does any of the reported file activity seem suspicious?
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options:
        - "Yes"
        - "No"
        optionsarg: []
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      - id: "1"
        label: ""
        labelarg:
          simple: What are the reasons for your answer?
        required: false
        gridcolumns: []
        defaultrows: []
        type: longText
        options: []
        optionsarg: []
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: Possible data exposure risk detected
      description: This alert requires a review regarding data exposure.
      sender: Your SOC team
      expired: false
      totalanswers: 0
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 88398c38-0edb-4dde-81bf-a2b59cebd1b1
    type: condition
    task:
      id: 88398c38-0edb-4dde-81bf-a2b59cebd1b1
      version: -1
      name: Is Code42 Available?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: brand
                      iscontext: true
                    right:
                      value:
                        simple: Code42
                - - operator: isEqualString
                    left:
                      value:
                        simple: state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 20,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 582abaef-dc9a-49a2-8846-4ad2b2867f76
    type: condition
    task:
      id: 582abaef-dc9a-49a2-8846-4ad2b2867f76
      version: -1
      name: Did the recipient say it is suspicious?
      description: Did the recipient say it is suspicious?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "No":
      - "2"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: Possible data exposure risk detected
                accessor: Answers.0
                transformers:
                - operator: toUpperCase
            iscontext: true
          right:
            value:
              simple: "YES"
    - label: "No"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: Possible data exposure risk detected
                accessor: Answers.0
                transformers:
                - operator: toUpperCase
            iscontext: true
          right:
            value:
              simple: "NO"
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 270c7373-9525-4b1c-8df4-2b87e7a34234
    type: collection
    task:
      id: 270c7373-9525-4b1c-8df4-2b87e7a34234
      version: -1
      name: Decide Remediation Action
      description: Decide remediation action
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 240,
          "y": 1200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
      subject:
      body:
        simple: What remediation action(s) would you like to take on ${inputs.Username}?
      methods: []
      format: ""
      bcc:
      cc:
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: 'Which remediation action(s) should be taken on this user? Notes from recipient: ${Possible data exposure risk detected.Answers.1}'
        required: true
        gridcolumns: []
        defaultrows: []
        type: multiSelect
        options: []
        optionsarg:
        - simple: BLOCK
        - simple: ADD-TO-WATCHLIST
        - simple: ADD-TO-LEGAL-HOLD
        fieldassociated: ""
        placeholder: ""
        tooltip: Select one or more actions from Block, Add-to-legal-hold, Add-to-Watchlist
        readonly: false
      title: Remediation Task
      description: ""
      sender: ""
      expired: false
      totalanswers: 0
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 7bcea75b-826e-4acc-86a3-8bccacea22dc
    type: playbook
    task:
      id: 7bcea75b-826e-4acc-86a3-8bccacea22dc
      version: -1
      name: Code42 Suspicious Activity Action
      description: Take corrective actions against a Code42 user found to be exposing file data.
      playbookName: Code42 Suspicious Activity Action
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      action:
        complex:
          root: Remediation Task
          accessor: Answers.0
          transformers:
          - operator: toUpperCase
      mattername:
        simple: ${inputs.LegalHoldMatterId}
      username:
        simple: ${inputs.Username}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 240,
          "y": 1350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 3ff98d31-796a-4a82-8cad-9a676d015963
    type: regular
    task:
      id: 3ff98d31-796a-4a82-8cad-9a676d015963
      version: -1
      name: ConvertTableToHTML
      description: Converts a given array to an HTML table
      scriptName: ConvertTableToHTML
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      table:
        simple: ${Code42.SecurityData}
      title:
        simple: Exposed Files
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 705
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: f18d9899-1305-4cdb-841e-285f3855afaa
    type: condition
    task:
      id: f18d9899-1305-4cdb-841e-285f3855afaa
      version: -1
      name: Were exposure events found?
      description: Checks if exposure events were found.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: greaterThan
          left:
            value:
              complex:
                root: Code42
                accessor: SecurityData.EventID
                transformers:
                - operator: count
            iscontext: true
          right:
            value:
              simple: "0"
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 525
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1505,
        "width": 640,
        "x": -20,
        "y": 50
      }
    }
  }
inputs:
- key: Username
  value:
    simple: ${incident.code42username}
  required: true
  description: The username of the employee.
  playbookInputQuery:
- key: ReviewerEmail
  value: {}
  required: true
  description: The email recipient to review potential suspicious activity related to the user, such as the user's manager.
  playbookInputQuery:
- key: LegalHoldMatterId
  value: {}
  required: false
  description: The legal hold matter ID to add the user to if selecting ADD-TO-LEGAL-HOLD in the Decide Remediation Action task.
  playbookInputQuery:
outputs: []
fromversion: 5.0.0
tests:
- Code42 Suspicious Activity Action Test
