id: a2335ce7-17b0-42d4-8f69-48bcfeb28a4d
description: A simple playbook for deactivating or reactivating a user in Code42.
inputs:
- description: Either "deactivate" or "reactivate"; the action you want to be done
    to the user.
  key: Action
  playbookInputQuery: null
  required: true
  value: {}
- description: The username of the user to deactivate or reactivate.
  key: Username
  playbookInputQuery: null
  required: true
  value: {}
name: Code42 Change User Activation
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 94f6760d-eacc-498d-8b1c-0d9aff499a08
      iscommand: false
      name: ""
      version: -1
    taskid: 94f6760d-eacc-498d-8b1c-0d9aff499a08
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Code42
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 38d4eed0-6ed4-4720-8c7f-7ea2f73f26d3
      iscommand: false
      name: Is Code42 Available?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 38d4eed0-6ed4-4720-8c7f-7ea2f73f26d3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 195
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Action
                transformers:
                - operator: toUpperCase
          operator: isEqualString
          right:
            value:
              simple: DEACTIVATE
      label: DEACTIVATE
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Action
                transformers:
                - operator: toUpperCase
          operator: isEqualString
          right:
            value:
              simple: REACTIVATE
      label: REACTIVATE
    id: "2"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "3"
      DEACTIVATE:
      - "5"
      REACTIVATE:
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 013b9275-f36c-49f4-8ad5-d3989cd6b088
      iscommand: false
      name: Is Deactivate or Reactivate?
      type: condition
      version: -1
    taskid: 013b9275-f36c-49f4-8ad5-d3989cd6b088
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7d22084e-bc48-4c9c-8af9-1e83d8901002
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 7d22084e-bc48-4c9c-8af9-1e83d8901002
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        simple: ${inputs.Username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Code42
      description: Reactivates the user with the given username.
      id: acd35060-92e6-4b7e-86b1-a2445679689a
      iscommand: true
      name: Code42 Reactivate User
      script: Code42|||code42-user-reactivate
      type: regular
      version: -1
    taskid: acd35060-92e6-4b7e-86b1-a2445679689a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        simple: ${inputs.Username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Code42
      description: Deactivate a user in Code42; signing them out of their devices.
        Backups discontinue for a deactivated user, and their archives go to cold
        storage.
      id: 410c35b8-5506-4b98-89e8-1f7602cc66bd
      iscommand: true
      name: Code42 Deactivate User
      script: Code42|||code42-user-deactivate
      type: regular
      version: -1
    taskid: 410c35b8-5506-4b98-89e8-1f7602cc66bd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_2_yes": 0.83
    },
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
