id: f1a0cdb1-feb8-4752-8502-0e5e8587c81f
inputs:
- description: The username to give to the newly created user.
  key: Username
  playbookInputQuery:
  required: true
  value: {}
- description: The email of the user to create.
  key: Email
  playbookInputQuery:
  required: true
  value: {}
- description: The name of the Code42 organization to create the user in.
  key: OrgName
  playbookInputQuery:
  required: true
  value: {}
name: Code42 Create User Playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b1876bae-e1fa-400e-8bd3-97ed9762ce39
      iscommand: false
      name: ""
      version: -1
    taskid: b1876bae-e1fa-400e-8bd3-97ed9762ce39
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Code42
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 35bc6954-feef-4e12-86b7-f57173635f0b
      iscommand: false
      name: Is Code42 Available?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 35bc6954-feef-4e12-86b7-f57173635f0b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      email:
        simple: ${inputs.Email}
      orgname:
        simple: ${inputs.OrgName}
      username:
        simple: ${inputs.Username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Code42
      description: Creates a Code42 user.
      id: 4734acef-5883-4e4b-85a1-0e36008c2ced
      iscommand: true
      name: Create User
      script: Code42|||code42-user-create
      type: regular
      version: -1
    taskid: 4734acef-5883-4e4b-85a1-0e36008c2ced
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 532d230b-7312-4430-8f2a-e1c8108c17fa
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 532d230b-7312-4430-8f2a-e1c8108c17fa
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 580
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 595,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
