description: This playbook downloads a file via Code42 by either MD5 or SHA256 hash.
id: Code42 File Download
inputs:
- description: MD5 hash to search for
  key: MD5
  playbookInputQuery:
  required: false
  value:
    complex:
      accessor: MD5
      root: File
      transformers:
      - operator: uniq
- description: SHA256 hash to search for
  key: SHA256
  playbookInputQuery:
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
      transformers:
      - operator: uniq
- description: The name of the file to save as.
  key: Filename
  playbookInputQuery:
  required: false
  value: {}
name: Code42 File Download
outputs: []
sourceplaybookid: Code42 File Search
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6d1ecdee-78b1-4275-8411-f802589a0a45
      iscommand: false
      name: ""
      version: -1
      description: ""
    taskid: 6d1ecdee-78b1-4275-8411-f802589a0a45
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Code42
                - - left:
                      iscontext: true
                      value:
                        simple: state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "1"
    ignoreworker: false
    nexttasks:
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks to see if a Code42 Integration is active.
      id: dc6b6ed4-b67e-46b2-8bf5-b2fbbc2e0d8e
      iscommand: false
      name: Is Code42 Integration Active?
      type: condition
      version: -1
    taskid: dc6b6ed4-b67e-46b2-8bf5-b2fbbc2e0d8e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.SHA256
          operator: isNotEmpty
      label: "yes"
    id: "2"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks to see if a SHA256 hash exists in the inputs.
      id: 7b90d431-46df-45ae-8e2c-d2e888bd6d9c
      iscommand: false
      name: Does SHA256 Exist?
      type: condition
      version: -1
    taskid: 7b90d431-46df-45ae-8e2c-d2e888bd6d9c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 545
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.MD5
          operator: isNotEmpty
      label: "yes"
    id: "3"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks to see if a MD5 hash exists in the inputs.
      id: a6ccfe5a-31b5-4bb1-81c4-6eeadf53420e
      iscommand: false
      name: Does MD5 Exist?
      type: condition
      version: -1
    taskid: a6ccfe5a-31b5-4bb1-81c4-6eeadf53420e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 370
        }
      }
  "5":
    continueonerror: true
    evidencedata:
      customfields: {}
      description:
        simple: The file that caused the alert.
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      filename:
        simple: ${inputs.Filename}
      hash:
        simple: ${inputs.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Code42
      description: Downloads a file from Code42 servers.
      id: 577615d3-3345-4ecc-8a37-a7d36ae6f898
      iscommand: true
      name: Code42 Download by SHA256
      script: Code42|||code42-download-file
      type: regular
      version: -1
    taskid: 577615d3-3345-4ecc-8a37-a7d36ae6f898
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "6":
    continueonerror: true
    evidencedata:
      customfields: {}
      description:
        simple: The file that caused the alert.
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      filename:
        simple: ${inputs.Filename}
      hash:
        simple: ${inputs.MD5}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Code42
      description: Downloads a file from Code42 servers.
      id: c1c84eb4-4b64-41d0-8b07-99be768b4c53
      iscommand: true
      name: Code42 Download by MD5
      script: Code42|||code42-download-file
      type: regular
      version: -1
    taskid: c1c84eb4-4b64-41d0-8b07-99be768b4c53
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 05d51ceb-6a80-4e24-8264-f43e2865ffdb
      iscommand: false
      name: Complete
      type: title
      version: -1
      description: ""
    taskid: 05d51ceb-6a80-4e24-8264-f43e2865ffdb
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 922.5,
        "x": 50,
        "y": 50
      }
    }
  }
fromversion: 5.0.0
tests:
- No Test
