id: Remove Employees from Departing Employee Watchlist
version: -1
name: Remove Employees from Departing Employee Watchlist
description: Loops through Departing Employee watchlist entries from Code42 Incydr and removes employees based on specified criteria.
tags:
- Code42 Incydr
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1bc56656-3cfd-448a-8a6f-5c138f4e09ae
    type: start
    task:
      id: 1bc56656-3cfd-448a-8a6f-5c138f4e09ae
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 460,
          "y": 0
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 507fad4f-f750-4fec-8c96-acf7b38ba7c5
    type: condition
    task:
      id: 507fad4f-f750-4fec-8c96-acf7b38ba7c5
      version: -1
      name: Is Departure Date More Than 30 Days Ago?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "15"
      "Yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "Yes"
      condition:
      - - operator: isBefore
          left:
            value:
              complex:
                root: inputs.incydr_departure_date
                transformers:
                - operator: DateStringToISOFormat
                  args:
                    add_utc_timezone: {}
                    dayfirst:
                      value:
                        simple: "false"
                    fuzzy: {}
                    yearfirst:
                      value:
                        simple: "true"
            iscontext: true
          right:
            value:
              complex:
                root: incident
                accessor: created
                transformers:
                - operator: ModifyDateTime
                  args:
                    variation:
                      value:
                        simple: 30 days ago
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 460,
          "y": 140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 31697334-8819-49df-8969-988696cdc340
    type: regular
    task:
      id: 31697334-8819-49df-8969-988696cdc340
      version: -1
      name: Remove User from Departing Employee Watchlist
      description: Removes a user from the Departing Employee List.
      script: Code42|||code42-departingemployee-remove
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#error#':
      - "13"
      '#none#':
      - "17"
    scriptarguments:
      username:
        simple: ${inputs.incydr_username}
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 940,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: bb0b1067-6bee-4a47-8f87-5dcdca0b61e4
    type: regular
    task:
      id: bb0b1067-6bee-4a47-8f87-5dcdca0b61e4
      version: -1
      name: Check for Post-Departure File Events in Incydr
      description: Search for Code42 Incydr File Events
      script: Code42|||code42-file-events-search
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      add-to-context:
        simple: "true"
      json:
        simple: |-
          {
            "purpose": "USER_EXECUTED_SEARCH",
            "groups": [
              {
                "filterClause": "AND",
                "filters": [
                  {
                    "value": "P30D",
                    "operator": "WITHIN_THE_LAST",
                    "term": "@timestamp"
                  }
                ],
                "display": "{\"data\":{\"isMultivalue\":false},\"version\":\"v2\"}"
              },
              {
                "filterClause": "AND",
                "filters": [
                  {
                    "value": "${inputs.incydr_username}",
                    "operator": "IS",
                    "term": "user.email"
                  }
                ],
                "display": "{\"data\":{\"isMultivalue\":false},\"version\":\"v2\"}"
              }
            ],
            "pgSize": 100,
            "pgNum": 1,
            "srtKey": "@timestamp",
            "srtDir": "desc"
          }
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 700,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 0ea0fa9e-6f4b-47a9-82e7-5e3083696493
    type: condition
    task:
      id: 0ea0fa9e-6f4b-47a9-82e7-5e3083696493
      version: -1
      name: Are There Post-Departure File Events?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Code42.SecurityData.Source.domain
            iscontext: true
      - - operator: isEmpty
          left:
            value:
              simple: Code42.FileEvents
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 700,
          "y": 485
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 5a97c22e-ffb7-4839-8296-6360f81e4092
    type: regular
    task:
      id: 5a97c22e-ffb7-4839-8296-6360f81e4092
      version: -1
      name: Set "Error Removing" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Attempted to remove ${inputs.incydr_username} from Departing Employee watchlist but encountered an error.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1390,
          "y": 830
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: eca20a6a-f971-4cd3-8d15-8b0d23eedb0b
    type: regular
    task:
      id: eca20a6a-f971-4cd3-8d15-8b0d23eedb0b
      version: -1
      name: Set "Removed from Watchlist" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Removed ${inputs.incydr_username} from Departing Employee watchlist. Departure date of ${inputs.incydr_departure_date} is more than 30 days ago.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 940,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 13ab8d8c-4aef-449a-81d5-a801a7452709
    type: regular
    task:
      id: 13ab8d8c-4aef-449a-81d5-a801a7452709
      version: -1
      name: Set "No Action Taken" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: No action taken on ${inputs.incydr_username}. Departure date of ${inputs.incydr_departure_date} is within the past 30 days.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 230,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 0c7f850e-676b-4b9e-83bd-d9bf400c0ccb
    type: regular
    task:
      id: 0c7f850e-676b-4b9e-83bd-d9bf400c0ccb
      version: -1
      name: Set "Post-Departure Activity" Log Message
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Log
      value:
        simple: Not removing ${inputs.incydr_username} because of post-departure activity.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 470,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 30579462-f482-42b0-867d-3f62ee22a65d
    type: regular
    task:
      id: 30579462-f482-42b0-867d-3f62ee22a65d
      version: -1
      name: Update Incydr User Profile
      description: Update a user's risk profile.
      script: Code42|||code42-user-update-risk-profile
      type: regular
      iscommand: true
      brand: Code42
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      ignore-outputs:
        simple: "false"
      notes:
        complex:
          root: incident
          accessor: created
          transformers:
          - operator: Cut
            args:
              delimiter:
                value:
                  simple: T
              fields:
                value:
                  simple: "1"
          - operator: concat
            args:
              prefix:
                value:
                  simple: '[XSOAR] Removed from Departing Employee watchlist on '
              suffix:
                value:
                  simple: .
      username:
        simple: ${inputs.incydr_username}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 940,
          "y": 830
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: a0734bc3-5794-4073-82a5-4f4d4470e816
    type: regular
    task:
      id: a0734bc3-5794-4073-82a5-4f4d4470e816
      version: -1
      name: Delete Code42 Context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      key:
        simple: Code42
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 230,
          "y": 1170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: ad5e7ca8-8e43-40d3-8c37-96551ff8921e
    type: title
    task:
      id: ad5e7ca8-8e43-40d3-8c37-96551ff8921e
      version: -1
      name: Playbook Complete
      description: commands.local.cmd.set.incident
      type: title
      iscommand: false
      brand: Builtin
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 230,
          "y": 1350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "3_13_#error#": 0.55
    },
    "paper": {
      "dimensions": {
        "height": 1415,
        "width": 1540,
        "x": 230,
        "y": 0
      }
    }
  }
inputs:
- key: incydr_departure_date
  value: {}
  required: true
  description: The departure date (in YYYY-MM-DD format) provided by Code42 Incydr.
  playbookInputQuery:
- key: incydr_username
  value: {}
  required: true
  description: The username (in email format) provided by Code42 Incydr.
  playbookInputQuery:
- key: incydr_uid
  value: {}
  required: false
  description: The unique identifier of a user provided by Code42 Incydr (optional).
  playbookInputQuery:
outputs: []
fromversion: 6.8.0
tests:
- Code42 File Search Test
